###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [ ]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [ ]:
get_state(4)

[[ 7 11  6  2]
 [ 0  3 15 14]
 [ 4  1  8 10]
 [ 9  5 13 12]]


[7, 11, 6, 2, 0, 3, 15, 14, 4, 1, 8, 10, 9, 5, 13, 12]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [ ]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if (state[i] > state[j])and (state[j]!=0): 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [ ]:
s = get_state(4)
count_inversion(s)

[[10  9  0 15]
 [ 3  6  2 14]
 [ 4  8  5 13]
 [ 1  7 12 11]]
[10, 9, 0, 15, 3, 6, 2, 14, 4, 8, 5, 13, 1, 7, 12, 11]


54

# **Find blank row**

In [ ]:
# find row position of the blank tile
import math
def get_blank_row(state):
  # define here
  d=math.sqrt(len(state))
  #print(d)
  #for i in range(len(state)):
  i=state.index(0)

    #if state[i]==0:
  return (math.floor(d-((i+1)/d)))+1




In [ ]:
i=4
d=4
math.floor(d-((i+1)/d))+1

3

In [ ]:
s = get_state(4)
get_blank_row(s)

[[15  5 13  4]
 [ 2 10 14  3]
 [12  6  0  7]
 [11  9  8  1]]


2

# Solvability Rules

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
  N = math.sqrt(len(initialState))
  print(N)
  I = count_inversion(initialState)#call function here
  
  print(I)
  R = get_blank_row(initialState)#call function here
  print(R)
  # decide solvability
  ne=False

  ie=False

  re=False

  if(N%2==0):
    ne=True
  if(I%2==0):
    ie=True
  if(R%2==0):
    re=True

  
  if(ne==False and ie==True):
    return True
  if(ne==True and re==False and ie==True):
    return True
  if(ne==True and re==True and ie==False):
    return True
    
  return False

  


In [ ]:
while True:
 S = get_state(5)
 #print(isSolvable(S))
 if isSolvable(S)==True:
   break


[[21 19 12 13 17]
 [15  0 22 20  8]
 [ 2 11  1 10 14]
 [ 5  6 24 18  4]
 [16  9  7 23  3]]
5.0
[21, 19, 12, 13, 17, 15, 0, 22, 20, 8, 2, 11, 1, 10, 14, 5, 6, 24, 18, 4, 16, 9, 7, 23, 3]
167
4
[[10  5 16  8 24]
 [ 3 14  7  9  6]
 [23 20 21 12 13]
 [22  4  1 19 15]
 [11 18  2  0 17]]
5.0
[10, 5, 16, 8, 24, 3, 14, 7, 9, 6, 23, 20, 21, 12, 13, 22, 4, 1, 19, 15, 11, 18, 2, 0, 17]
134
1
